#!/bin/bash -e

if [[ $# -lt 1 ]]; then
  echo "Usage: ${0##*/} CMD [ARG]..." >&2
  exit 64
fi

if [[ $UID -eq 0 ]]; then
  exec unshare --user --map-auto --setuid=0 --setgid=0 -- "$@"
else
  exec unshare --user --map-auto --map-root-user -- "$@"
fi
